tap "bjarneo/cliamp"

brew "bat"
brew "btop"
brew "bjarneo/cliamp/cliamp", trusted: true
brew "eza"
brew "fd"
brew "fastfetch"
brew "fzf"
brew "gh"
brew "jq"
brew "lazygit"
brew "neovim"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "yazi"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

cask "font-symbols-only-nerd-font"
cask "ghostty"
